#!/bin/bash
# First copy all the SVG files from individual directories into the pwd
# and rename them 
cp ad/vector.svg ad.svg
cp ae/vector.svg ae.svg
cp af/vector.svg af.svg
cp ag/vector.svg ag.svg
cp ai/vector.svg ai.svg
cp al/vector.svg al.svg
cp am/vector.svg am.svg
cp ao/vector.svg ao.svg
cp aq/vector.svg aq.svg
cp ar/vector.svg ar.svg
cp as/vector.svg as.svg
cp at/vector.svg at.svg
cp au/vector.svg au.svg
cp aw/vector.svg aw.svg
cp ax/vector.svg ax.svg
cp az/vector.svg az.svg
cp ba/vector.svg ba.svg
cp bb/vector.svg bb.svg
cp bd/vector.svg bd.svg
cp be/vector.svg be.svg
cp bf/vector.svg bf.svg
cp bg/vector.svg bg.svg
cp bh/vector.svg bh.svg
cp bi/vector.svg bi.svg
cp bj/vector.svg bj.svg
cp bl/vector.svg bl.svg
cp bm/vector.svg bm.svg
cp bn/vector.svg bn.svg
cp bo/vector.svg bo.svg
cp bq/vector.svg bq.svg
cp br/vector.svg br.svg
cp bs/vector.svg bs.svg
cp bt/vector.svg bt.svg
cp bv/vector.svg bv.svg
cp bw/vector.svg bw.svg
cp by/vector.svg by.svg
cp bz/vector.svg bz.svg
cp ca/vector.svg ca.svg
cp cc/vector.svg cc.svg
cp cd/vector.svg cd.svg
cp cf/vector.svg cf.svg
cp cg/vector.svg cg.svg
cp ch/vector.svg ch.svg
cp ci/vector.svg ci.svg
cp ck/vector.svg ck.svg
cp cl/vector.svg cl.svg
cp cm/vector.svg cm.svg
cp cn/vector.svg cn.svg
cp co/vector.svg co.svg
cp cr/vector.svg cr.svg
cp cu/vector.svg cu.svg
cp cv/vector.svg cv.svg
cp cw/vector.svg cw.svg
cp cx/vector.svg cx.svg
cp cy/vector.svg cy.svg
cp cz/vector.svg cz.svg
cp de/vector.svg de.svg
cp dj/vector.svg dj.svg
cp dk/vector.svg dk.svg
cp dm/vector.svg dm.svg
cp do/vector.svg do.svg
cp dz/vector.svg dz.svg
cp ec/vector.svg ec.svg
cp ee/vector.svg ee.svg
cp eg/vector.svg eg.svg
cp eh/vector.svg eh.svg
cp er/vector.svg er.svg
cp es/vector.svg es.svg
cp et/vector.svg et.svg
cp fi/vector.svg fi.svg
cp fj/vector.svg fj.svg
cp fk/vector.svg fk.svg
cp fo/vector.svg fo.svg
cp fr/vector.svg fr.svg
cp ga/vector.svg ga.svg
cp gb/vector.svg gb.svg
cp gd/vector.svg gd.svg
cp ge/vector.svg ge.svg
cp gf/vector.svg gf.svg
cp gg/vector.svg gg.svg
cp gh/vector.svg gh.svg
cp gi/vector.svg gi.svg
cp gl/vector.svg gl.svg
cp gm/vector.svg gm.svg
cp gn/vector.svg gn.svg
cp gp/vector.svg gp.svg
cp gq/vector.svg gq.svg
cp gr/vector.svg gr.svg
cp gs/vector.svg gs.svg
cp gt/vector.svg gt.svg
cp gu/vector.svg gu.svg
cp gw/vector.svg gw.svg
cp gy/vector.svg gy.svg
cp hk/vector.svg hk.svg
cp hm/vector.svg hm.svg
cp hn/vector.svg hn.svg
cp hr/vector.svg hr.svg
cp ht/vector.svg ht.svg
cp hu/vector.svg hu.svg
cp id/vector.svg id.svg
cp ie/vector.svg ie.svg
cp il/vector.svg il.svg
cp im/vector.svg im.svg
cp in/vector.svg in.svg
cp io/vector.svg io.svg
cp iq/vector.svg iq.svg
cp ir/vector.svg ir.svg
cp is/vector.svg is.svg
cp it/vector.svg it.svg
cp jm/vector.svg jm.svg
cp jo/vector.svg jo.svg
cp jp/vector.svg jp.svg
cp ke/vector.svg ke.svg
cp kg/vector.svg kg.svg
cp kh/vector.svg kh.svg
cp ki/vector.svg ki.svg
cp km/vector.svg km.svg
cp kn/vector.svg kn.svg
cp kp/vector.svg kp.svg
cp kr/vector.svg kr.svg
cp kw/vector.svg kw.svg
cp ky/vector.svg ky.svg
cp kz/vector.svg kz.svg
cp la/vector.svg la.svg
cp lb/vector.svg lb.svg
cp lc/vector.svg lc.svg
cp li/vector.svg li.svg
cp lk/vector.svg lk.svg
cp lr/vector.svg lr.svg
cp ls/vector.svg ls.svg
cp lt/vector.svg lt.svg
cp lu/vector.svg lu.svg
cp lv/vector.svg lv.svg
cp ly/vector.svg ly.svg
cp ma/vector.svg ma.svg
cp mc/vector.svg mc.svg
cp md/vector.svg md.svg
cp me/vector.svg me.svg
cp mf/vector.svg mf.svg
cp mg/vector.svg mg.svg
cp mk/vector.svg mk.svg
cp ml/vector.svg ml.svg
cp mm/vector.svg mm.svg
cp mn/vector.svg mn.svg
cp mo/vector.svg mo.svg
cp mq/vector.svg mq.svg
cp mr/vector.svg mr.svg
cp ms/vector.svg ms.svg
cp mt/vector.svg mt.svg
cp mu/vector.svg mu.svg
cp mv/vector.svg mv.svg
cp mw/vector.svg mw.svg
cp mx/vector.svg mx.svg
cp my/vector.svg my.svg
cp mz/vector.svg mz.svg
cp na/vector.svg na.svg
cp nc/vector.svg nc.svg
cp ne/vector.svg ne.svg
cp nf/vector.svg nf.svg
cp ng/vector.svg ng.svg
cp ni/vector.svg ni.svg
cp nl/vector.svg nl.svg
cp no/vector.svg no.svg
cp np/vector.svg np.svg
cp nr/vector.svg nr.svg
cp nu/vector.svg nu.svg
cp nz/vector.svg nz.svg
cp om/vector.svg om.svg
cp pa/vector.svg pa.svg
cp pe/vector.svg pe.svg
cp pf/vector.svg pf.svg
cp pg/vector.svg pg.svg
cp ph/vector.svg ph.svg
cp pk/vector.svg pk.svg
cp pl/vector.svg pl.svg
cp pm/vector.svg pm.svg
cp pn/vector.svg pn.svg
cp pr/vector.svg pr.svg
cp pt/vector.svg pt.svg
cp pw/vector.svg pw.svg
cp py/vector.svg py.svg
cp qa/vector.svg qa.svg
cp re/vector.svg re.svg
cp ro/vector.svg ro.svg
cp rs/vector.svg rs.svg
cp ru/vector.svg ru.svg
cp rw/vector.svg rw.svg
cp sa/vector.svg sa.svg
cp sb/vector.svg sb.svg
cp sc/vector.svg sc.svg
cp sd/vector.svg sd.svg
cp se/vector.svg se.svg
cp sg/vector.svg sg.svg
cp sh/vector.svg sh.svg
cp si/vector.svg si.svg
cp sj/vector.svg sj.svg
cp sk/vector.svg sk.svg
cp sl/vector.svg sl.svg
cp sm/vector.svg sm.svg
cp sn/vector.svg sn.svg
cp so/vector.svg so.svg
cp sr/vector.svg sr.svg
cp ss/vector.svg ss.svg
cp st/vector.svg st.svg
cp sv/vector.svg sv.svg
cp sx/vector.svg sx.svg
cp sy/vector.svg sy.svg
cp sz/vector.svg sz.svg
cp tc/vector.svg tc.svg
cp td/vector.svg td.svg
cp tf/vector.svg tf.svg
cp tg/vector.svg tg.svg
cp th/vector.svg th.svg
cp tj/vector.svg tj.svg
cp tk/vector.svg tk.svg
cp tl/vector.svg tl.svg
cp tm/vector.svg tm.svg
cp tn/vector.svg tn.svg
cp to/vector.svg to.svg
cp tr/vector.svg tr.svg
cp tt/vector.svg tt.svg
cp tw/vector.svg tw.svg
cp tz/vector.svg tz.svg
cp ua/vector.svg ua.svg
cp ug/vector.svg ug.svg
cp us/vector.svg us.svg
cp uy/vector.svg uy.svg
cp uz/vector.svg uz.svg
cp va/vector.svg va.svg
cp vc/vector.svg vc.svg
cp ve/vector.svg ve.svg
cp vg/vector.svg vg.svg
cp vi/vector.svg vi.svg
cp vn/vector.svg vn.svg
cp vu/vector.svg vu.svg
cp wf/vector.svg wf.svg
cp ws/vector.svg ws.svg
cp ye/vector.svg ye.svg
cp yt/vector.svg yt.svg
cp za/vector.svg za.svg
cp zm/vector.svg zm.svg
cp zw/vector.svg zw.svg

#Convert all the SVGs to PNGs. These come out as 1024x1024 images, which is a good size to convert
mogrify -format png *.svg

#Convert to ASCII art. Braille characters tends to best represent distinct shape of a country's borders
ascii-image-converter *.png -b -n -W 60 --save-txt .

#rename them all to be named "[ISO 3166 code].txt"
rename 's/([a-z]{2})[a-z\-]+\.txt/$1.txt/g' *.txt

mkdir -p output
mv *.txt output/.
